# Generated by Django 5.2.3 on 2025-06-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chicago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, default='Sin especificar', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Necesita especificar', max_length=20),
        ),
    ]
